# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ dev]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Virtual env creation
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requirements.txt
  test:
    needs: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10"]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Flake8
        run: |
            pip install flake8
            flake8 --exclude='.venv' --extend-ignore=E501
            
      - name: pytest
        run: |
            pip install pytest-cov
            python -m pytest --doctest-modules --ignore=main.py --cov
  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: ${{github.ref_name == 'main'}}
    steps:
      - name: Chekout repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "excelia-tp-1"
          heroku_email: "othmanechahid1@gmail.com"
          
  deploy_dev:
    needs: test
    runs-on: ubuntu-latest
    if: ${{github.ref_name == 'dev'}}
    steps:
      - name: Chekout repository
        uses: actions/checkout@v2
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "excelia-tp-1-dev"
          heroku_email: "othmanechahid1@gmail.com"
  test_status_code:
  # This workflow contains a single job called "build"
    needs: deploy
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Statuscode
        run: |
          pip install requests
          python3 -c "import requests; exit(1) if requests.get('https://excelia-tp-1.herokuapp.com').status_code !=200 else exit(0)"
 
  test_status_code_dev:
  # This workflow contains a single job called "build"
    needs: deploy_dev
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Runs a set of commands using the runners shell
      - name: Statuscode
        run: |
          pip install requests
          python3 -c "import requests; exit(1) if requests.get('https://excelia-tp-1.herokuapp.com').status_code !=200 else exit(0)"
       
